services:
  server:
    container_name: relaygate
    image: sunjay195/relaygate:latest
    build:
      context: .
    ports:
      - 4200:4000
    env_file:
      - .env
    restart: unless-stopped
